# Generated by Django 5.2.6 on 2025-09-13 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('regiao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MetricasModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mae', models.FloatField()),
                ('rmse', models.FloatField()),
                ('mape', models.FloatField()),
                ('data_calculo', models.DateTimeField(auto_now=True)),
                ('municipio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='DadosEvasao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('total', models.FloatField()),
                ('serie_1', models.FloatField(blank=True, null=True)),
                ('serie_2', models.FloatField(blank=True, null=True)),
                ('serie_3', models.FloatField(blank=True, null=True)),
                ('serie_4', models.FloatField(blank=True, null=True)),
                ('nao_seriado', models.FloatField(blank=True, null=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.municipio')),
            ],
            options={
                'unique_together': {('municipio', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='PrevisaoEvasao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('previsao', models.FloatField()),
                ('limite_inferior', models.FloatField()),
                ('limite_superior', models.FloatField()),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.municipio')),
            ],
            options={
                'unique_together': {('municipio', 'ano')},
            },
        ),
    ]
